#include"substitution/monoalphabetic ciphers/affinecipher.h"
#include"substitution/polyalphabetic ciphers/autokeycipher.h"
#include"substitution/polyalphabetic ciphers/vigenerecipher.h"
#include"substitution/polyalphabetic ciphers/rotorcipher.h"
#include"transposition/railfencecipher.h"
#include"encryption.h"
#include"decryption.h"
